# Copyright (c) 2026, Trustbit Software and contributors
# /staff — shell for the KGS Staff app PWA (Vue, built from frontend/).
#
# Serves the shell (www/staff.html, GENERATED by frontend/scripts/postbuild.mjs
# — never hand-edit it) to Guest and signed-in users alike, because the login
# screen must render for Guest. No business data here: every read happens
# later over /api through staff_app/api.py, which re-checks everything.

import json

import frappe
import frappe.sessions

from trustbit_school_book_seller.staff_app.api import app_enabled, sw_enabled, user_allowed

# Never serve a Redis-cached shell that points at an old bundle.
no_cache = 1


def get_context(context):
	# CSRF token generation is lazy and a standalone www page triggers nothing
	# else that creates it — without this the <!-- csrf_token --> marker injects
	# an empty token and every POST fails. Commit: the token lives in the
	# session store (same as frappe/www/app.py).
	frappe.sessions.get_csrf_token()
	frappe.db.commit()

	# Rendered into window.staffEnv. No ".__" anywhere in the template: frappe's
	# safe_render rejects it as "Illegal template".
	context.staff_enabled = 1 if app_enabled() else 0
	context.staff_sw = 1 if sw_enabled() else 0
	# Guest must render as allowed (this page IS the login screen); login ends
	# in a full reload, which recomputes this for the real user. Presentation
	# only — every endpoint re-checks the role.
	is_guest = frappe.session.user in (None, "", "Guest")
	context.staff_allowed = 1 if (is_guest or user_allowed()) else 0
	# Who is signed in, so the app needs no whoami round-trip on launch (for a
	# Guest that call is a 403). JSON string; "<" escaped so it can never
	# close the <script> tag.
	context.staff_user = json.dumps(frappe.session.user or "Guest").replace("<", "\\u003c")
	return context
